# Generated by Django 6.0.5 on 2026-05-09 07:27

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Causa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('causa_nome', models.CharField(max_length=100)),
                ('causa_descricao', models.TextField()),
                ('causa_nrVotos', models.IntegerField(default=0)),
                ('causa_estado', models.IntegerField(default=0)),
                ('causa_responsavel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='CausaVoto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('causaVoto_dataVoto', models.DateTimeField()),
                ('causaVoto_causa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='causas.causa')),
                ('causaVoto_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Evento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('evento_name', models.CharField(max_length=100)),
                ('evento_descricao', models.TextField()),
                ('evento_localizacao', models.TextField()),
                ('evento_dataHora', models.DateTimeField()),
                ('evento_limiteParticipantes', models.IntegerField(default=0)),
                ('evento_lotado', models.BooleanField(default=False)),
                ('evento_ativo', models.BooleanField(default=False)),
                ('evento_causa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='causas.causa')),
            ],
        ),
        migrations.CreateModel(
            name='Comentario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comentario_texto', models.TextField()),
                ('comentario_dataComentario', models.DateTimeField()),
                ('comentario_causa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='causas.causa')),
                ('comentario_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('comentario_evento', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='causas.evento')),
            ],
        ),
        migrations.CreateModel(
            name='LikeComentario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('likeComentario_dataLike', models.DateTimeField()),
                ('likeComentario_comentario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='causas.comentario')),
                ('likeComentario_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Participante',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('participante_dataInscricao', models.DateTimeField()),
                ('participante_causa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='causas.evento')),
                ('participante_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
