# Generated by Django 6.0.5 on 2026-05-09 07:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('causas', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='participante',
            old_name='participante_causa',
            new_name='participante_evento',
        ),
    ]
