# Generated by Django 6.0.5 on 2026-05-09 07:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('causas', '0002_rename_participante_causa_participante_participante_evento'),
    ]

    operations = [
        migrations.RenameField(
            model_name='evento',
            old_name='evento_name',
            new_name='evento_nome',
        ),
    ]
