# Generated by Django 6.0.5 on 2026-05-09 08:52

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('causas', '0003_rename_evento_name_evento_evento_nome'),
    ]

    operations = [
        migrations.AlterField(
            model_name='causavoto',
            name='causaVoto_dataVoto',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='comentario',
            name='comentario_dataComentario',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='evento',
            name='evento_dataHora',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='likecomentario',
            name='likeComentario_dataLike',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='participante',
            name='participante_dataInscricao',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
