# Generated by Django 6.0.5 on 2026-05-24 21:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('causas', '0005_evento_evento_criador'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comentario',
            name='comentario_causa',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='causas.causa'),
        ),
        migrations.AlterField(
            model_name='comentario',
            name='comentario_evento',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='causas.evento'),
        ),
    ]
