# Generated by Django 6.0.5 on 2026-05-25 06:19

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('causas', '0006_alter_comentario_comentario_causa_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='causavoto',
            constraint=models.UniqueConstraint(fields=('causaVoto_causa', 'causaVoto_user'), name='unique_voto_por_user_causa'),
        ),
    ]
