# Generated by Django 6.0.5 on 2026-05-25 16:38

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('causas', '0007_causavoto_unique_voto_por_user_causa'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='likecomentario',
            constraint=models.UniqueConstraint(fields=('likeComentario_user', 'likeComentario_comentario'), name='unique_like_por_user_comentario'),
        ),
    ]
